manifest:
  remotes:
  - name: zmkfirmware
    url-base: https://github.com/zmkfirmware
  - name: takumibaya
    url-base: https://github.com/takumibaya
  - name: halfdane
    url-base: https://github.com/halfdane/
  projects:
  - name: zmk
    remote: zmkfirmware
    revision: main
    import: app/west.yml
  - name: zmk-input-gestures
    remote: halfdane
    revision: main
  self:
    path: config
